### PR TITLE
Factory blueprintability

### PR DESCRIPTION
**Pull request by jimrandomh**
This patch makes factories blueprint-able. When you research the technology, you can put a "factory construction requester chest" next to any factory; this will look at a factory next to it for blueprint ghosts, use its contents to build those ghosts, and request those items from the logistic network. When you create a blueprint, if it contains a factory building with a construction requester chest next to it, the blueprint will contain a "factory contents marker" in place of the chest, which contains a blueprint string for the contents of the factory next to it; when the factory is placed, the blueprint will be applied and the factory contents marker will be turned back into a construction requester chest.

Known minor issues:

 * Strings have not been localized to non-English languages.
 * The factory construction requester chest is reusing graphics from the factory requester chest, as is its technology.
 * Blueprint modification is done when you confirm the blueprint, rather than when you drag-create it, so if you export a blueprint to string from the confirmation dialog without confirming first it won't have factory content information in it.
 * Blueprints do not contain building power settings or connection settings.
 * The "instant blueprint" cheat (in creative mode) interferes with filling blueprinted factory buildings.
 * When a blueprinted factory building is placed, the factory construction requester chest is free.

### CODE REVIEW

**Comment by MagmaMcFry** [comment]
Nice! Unfortunately, checking and pulling this will have to wait until I have time for this stuff again, but I appreciate the effort.

**Comment by Nexela** [comment]
> The "instant blueprint" cheat (in creative mode) interferes with filling blueprinted factory buildings.

What is the issue with instant blueprints?

**Comment by jimrandomh** [comment]
> What is the issue with instant blueprints?

If instant-blueprint is on, the Factory Contents Marker doesn't get replaced with a Factory Construction Requester Chest like it's supposed to be.

**Comment by jimrandomh** [comment]
Mind if I publish this as "Factorissimo3", with the Author field in info.json as "MagmaMcFry and jimrandomh"? (There are a couple small things I want to change first - mainly making the port markers visible in blueprint previews - after which I'm going to call this done.)

**Comment by MagmaMcFry** [comment]
Actually I would mind, please don't call it Factorissimo3. I'd prefer you'd name it to make it clear that it's a variant and not an official update: I'd suggest "Factorissimo2 Blueprintable Edition" for example. I haven't abandoned my mod yet, and I'd like to continue developing it, so having something called Factorissimo3 out there would just confuse the shit out of everyone.

I do encourage you to release it separately, because I've decided I'm not gonna pull this request into Factorissimo2, simply because your blueprinting and rotation mechanics, while amazing, have barrels of potential for unfixable bugs (not your fault, just API limits, you've probably encountered a lot by now) that I really don't wish to deal with, and will additionally break most other mods that rely on keeping track of scripted entities. Please include a warning about this type of mod incompatibility on the description page, just so people know what they're getting themselves into. I still foresee lots of incoming complaints about that.

I tried your variant out today, and I found a bug or four after minimal testing of rotating factory buildings: rotating a factory containing dropped items causes a crash, rotating a factory with nonempty transport belts causes the items to drop, rotating a train doesn't work and will cause a crash when another entity rotates onto the train, and circuit connections aren't preserved. Still, your improvements are amazing and I'm impressed you've made it this far. Good luck!

**Pull request closed without merging**
