### PR TITLE
Fix factoriomaps API name mismatch

### PR DESCRIPTION
**Pull request by dnsdhrj**
My factorissimo-factoriomap compatibility is broken due to API name mismatch.
I've done something wrong with other mods, or this commit will fix the issue.

### CODE REVIEW

**Comment by dnsdhrj** [comment]
See factoriomaps code here:

https://github.com/L0laapk3/FactorioMaps/blob/06efafbc9aafdb2031fdc97c1855924f0978cf5f/api.lua#L130-L133

**Comment by L0laapk3** [comment]
Hey there! I'm the developer of factoriomaps, I havent been able to publish factoriomaps with API yet. This means that factorissimo is trying to call API objects that don't exist yet. Sorry about that!

You can either wait for release 3.5.0, or try the [dev branch](https://github.com/L0laapk3/FactorioMaps/tree/dev).

**Comment by L0laapk3** [comment]
Upon further inspectation, Ive found that the API that made it into release 3.4.0 is accidental, its a dummy API that does nothing and shouldn't have been in the 3.4.0 release. Again, apologies!

**Comment by dnsdhrj** [comment]
With current mod versions, factoriomaps `auto.py` crashes when factorissimo is enabled.
This commit fixes crash.
crash

**Comment by L0laapk3** [comment]
The name factorissimo uses is correct. Factoriomaps 3.4.0 was accidentally released with a mockup version of the API that does nothing. It wasn't supposed to be there at all, then there would be a different error of trying to call an API that doesn't exist at all. I was supposed to release factoriomaps 3.5.0 at the same time as factorissimo, but I had some last minute hold ups. Sorry about this, I'm working on it!

**Comment by dnsdhrj** [comment]
OK, then I will close this :)

**Comment by L0laapk3** [comment]
Just letting you know that I finally managed to get that multi hour session in to track down those last stubborn bugs and roll out FactorioMaps 3.5.0 :)

**Pull request closed without merging**
